6 - Em um campeonato de futebol, existem vários times e cada um possui diversos 
jogadores. Faça um programa que receba a idade, o peso e a altura de cada um dos 
jogadores, calcule e mostre:
A. a quantidade de jogadores com idade inferior a 18 anos;
B. a média das idades dos jogadores;
C. a média das alturas de todos os jogadores do campeonato;
D. a quantidade de jogadores com mais de 80 quilos entre todos os 
jogadores do campeonato.
O sistema deve finalizar a entrada de dados quando a idade for igual a 0.